---
abstract: 'A lightweight jq-like JSON query engine in Perl'
author:
  - 'Kawamura Shingo <pannakoota1@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: JQ-Lite
no_index:
  directory:
    - t
    - inc
    - t
    - inc
requires:
  FindBin: '0'
  Getopt::Long: '0'
  IO::File: '0'
  JSON::PP: '0'
  List::Util: '0'
  Scalar::Util: '0'
  Term::ANSIColor: '0'
  Test::More: '0'
  perl: '5.014'
resources:
  bugtracker: https://github.com/kawamurashingo/JQ-Lite/issues
  repository: https://github.com/kawamurashingo/JQ-Lite.git
version: '1.31'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
